### ISSUE TITLE
[TASK] Crate restructure

### ISSUE THREAD

**Issue by kurtlawrence** [kdr-aus/daedalus#113]
## Goal
With removal of the papyrus REPL and support for lib linking, crates can be restructured into more sensible dependencies.

## Aspects to Develop
- [ ] Remove `Extender` system (#114)
- [ ] Extract ipc into an `actions` crate (#115)
- [ ] Extract html into own crate (#116)
- [ ] Consolidate `parsing` deps (#117)
