### ISSUE TITLE
[TASK] Tracking issue for Book development

### ISSUE THREAD

**Issue by kurtlawrence** [kdr-aus/daedalus#12]
# Goal
Start on documentation in the Book.

# Aspects to Develop
- [x] Getting Started
- [x] Uri
- [ ] Kserd
- [ ] Kserd Charting 
- [ ] Kserd data structures (links to the API grammars?)
- [ ] Number formatting strings
- [ ] Table formatting examples

**Comment by kurtlawrence** [comment]
Book is no longer going to be support.ed
