### ISSUE TITLE
[TRACKING] Minimum Viable Product of Delivery System

### ISSUE THREAD

**Issue by kurtlawrence** [kdr-aus/daedalus#158]
Breakdown of aspects to get a minimum viable product for the delivery system.

**misc:**
- [x] Test access to two workspaces from same client (off same leto) (#160)
- [x] Extract common HTML and DOM to share between `daedalus` and `zeus`  (#159)
- [x] Create `zeus` landing page (#163)

**User Accounts:**
- [x] Create workspace, (#161)
- [x] Remove workspace, (#161)
- [x] Account creation, (#162)

**Maintenance - Zeus:**
- [x] Save `leto_map` to disk, (#164)
- [x] Save `aliases` to disk, (#164)
- [x] Periodically update `letos` from disk, (#164)
- [x] Remove expired aliases, (#164)

**Maintenance - Leto:**
- [x] Save `pwd_hashes` to disk, (#164)
- [x] Save `workspaces` to disk, (#164)
- [x] Clean `alias_auths` periodically (#164)

**Workspace Data:**
- [x] Upload file, (#165)
- [x] Create directory, (#165)
- [x] Delete file,  (#165)
- [x] Delete directory, (#165)
- [x] Upload container (zip, gzip, bzip2, 7z) (#166)
- [x] Create alias link, (#161)
