### ISSUE TITLE
[TRACKING] Open source ogma

### ISSUE THREAD

**Issue by kurtlawrence** [kdr-aus/daedalus#234]
- [x] Publish `numfmt` crate (#235)
- [x] Link `daedalus` to use public `numfmt` (#236)
- [x] Publish `DStr` (#237)
- [x] Public `table` crate (#238)
- [x] Remove repr dep (#239)
- [x] Disk caching (#240)
- [x] Extract `ogma` (#241)
