### ISSUE TITLE
[TASK] Tracking Issue: Removal of REPL

### ISSUE THREAD

**Issue by kurtlawrence** [kdr-aus/daedalus#90]
## Goal
The REPL will be removed to gain the following benefits:
- Less code maintenance
- Reduce bundling size
- Reduce bundling complexity
- Reduce dependency brittleness
- Remove rust pinning requirement

## Aspects to Develop
- [x] Remove Book (#87)
- [x] Remove API (#88)
- [x] Transition to new interface (#89)
- [x] Remove REPL with bin
- [x] Remove `papyrus` references
- [x] Clean up
- [ ] Switch to stable or beta rust version
